Warn on verification failure
* Now only warns when verification fails

diff --git a/sbscript b/sbscript
--- a/sbscript
+++ b/sbscript
@@ -21,8 +21,13 @@ SBCERT=
 
 # Print message and exit
 function die() {
-    echo "$@" 1>&2
+    echo "ERROR: $@" 1>&2
     exit 1
+}
+
+# Print warning
+function warn() {
+	echo "WARNING: $@" 1>&2
 }
 
 # Test whether variables are valid
@@ -74,7 +79,7 @@ if [[ $? = 0 ]]; then
     echo "OK"
 else
     echo "Failed"
-    die "Verification of signed efi executable failed."
+    warn "Verification of signed efi executable failed."
 fi
 
 # copy to destination
